baseURL = "https://www.mehvix.com/"
title = "welcome!"
theme ="hugo-theme-basic-customized"
languageCode = "en-us"
enableEmoji = true 
copyright = "© 2016-19 <a href='https://github.com/siegerts/hugo-theme-basic'>Hugo Theme Basic</a>. "
description = "Max Vogel's personal website."

publishDir = "docs"

[taxonomies]
  category = "categories"

[params]
  titleEmoji = ""

[Permalinks]
  post = "post/:slug"
  project = "project/:slug"

[[params.menu]]
  name = "about me"
  url = "about/"

[[params.menu]]
  name = "all posts"
  url = "post/"

[[params.menu]]
  name = "posts by category"
  url = "categories/"


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true