baseURL = "https://www.mehvix.com/"
title = "welcome!"
theme ="hugo-theme-basic-customized"
languageCode = "en-us"
enableEmoji = true 
# copyright = "© 2019 - Max Vogel"
# Instead I'm going to write some js in footers.html to auto-update the year
description = "Max Vogel's personal website."

publishDir = "docs"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ""

[Permalinks]
  post = "posts/:slug"
  tags = "tags/:slug"

[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "posts"
  url = "categories/"


[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true


[services.rss]
  limit = 15
